# Generated by Django 3.1.2 on 2020-11-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20201103_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
