# Generated by Django 3.1.2 on 2020-11-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_person_is_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Pseudonim'),
        ),
    ]
