# Generated by Django 3.1.2 on 2020-11-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20201103_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_man',
            field=models.BooleanField(default=False),
        ),
    ]
